# Checks that the package.json file has been updated
name: Check release version
on:
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get current release version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: ./
      - name: Get the latest release
        id: last_release
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          owner: Sanger
          repo: ui-styling
          excludes: prerelease, draft

      - name: Compare releases
        run: >-
          if [ "${{ steps.last_release.outputs.release }}" = "$(printf 'v%s\n' ${{ steps.package-version.outputs.current-version}})" ]; then
            exit 1;
          fi


      

   